### ISSUE TITLE
ability to share unmute page

### ISSUE THREAD

**Issue by fczuardi** [calamar-io/controltower#49]
customers should be able to share the unmute page with other people

In order to do that, some new features are necessary:

- [x] an interface for changing the current selected bot #51
- [x] a section for setting up an admin team for a bot with invite links #50
- [x] a page to accept invitations #70
