### ISSUE TITLE
[meta] UI for simple intents (SAC/mini-faq)

### ISSUE THREAD

**Issue by fczuardi** [calamar-io/controltower#59]
This will be the same replies sections, but with some extra fields for setting up the utterances.

Breaking it down in separate tasks we should:

- [x] create a new bot type "faq" in dynamo and an example line to be loaded
- [x] create a new UI panel for setting up questions/statements and grouping them in statements groups #73
- [x] UI for linking an existing answer to a statement group #80

**Comment by fczuardi** [comment]
format of the replies is similar/same of what we are using for the bot type ecommerce

**Comment by fczuardi** [comment]
PR with the fixes is made
